### ISSUE TITLE
해당 깃헙 블로그가 어떤 테마를 사용하는지요?

### ISSUE THREAD

**Issue by hellojinwoo** [ByeongsuPark/byeongsupark.github.io#5]
박병수님 안녕하세요. 하나 여쭈어봐도 될까요? 어떤 지킬 블로그 테마를 사용중이신지요?

혹시 tale 테마를 사용중이신건지요? 그런데 해당 테마의 데모사이트( https://chesterhow.github.io/tale/ )와는 차이가 많이 나보여서요. tale테마가 맞을까요?

 http://jihyeleee.com/ 이 분과 박병수님의 테마가 비슷해서요, 같은 테마를 사용하시는 것 같은데, 도통 찾아봐도 무슨 테마인지 모르겠네요...

감사합니다 ^^

**Comment by ByeongsuPark** [comment]
@hellojinwoo 님 안녕하세요.
이슈 확인하고 답변드립니다.

말씀하신 이지혜님의 블로그 테마가 맞습니다.
tale 테마에 기반하셔서 따로 작업하신 것으로 알고 있습니다.
템플릿 형식으로 배포하시지는 않는 걸로 알고 있습니다만,
관심 있으신 거 같아 [이지혜님 블로그 레포 링크](https://github.com/iamleejihye/iamleejihye.github.io) 걸어드립니다.
